---
- name: Install HTTP server
  hosts: g1
  become: yes

  tasks:
  - name: Install HTTPD
    yum:
      name: httpd
      state: present
      when: ansible _distribution == "Amazon" or ansible _distribution == "Centos"

  - name: Start HTTPD
    service:
      name: httpd
      state: started
      when: ansible _distribution == "Amazon" or ansible _distribution == "Centos"

  - name: Enable HTTPD
    service:
      name: httpd
      enabled: yes
      when: ansible _distribution == "Amazon" or ansible _distribution == "Centos"


  - name: Install Apache2
    apt:
      name: apache2
      state: present
      when: ansible _distribution == "Ubuntu" or ansible _distribution == "Debian"

  - name: Start Apache2
    service:
      name: apache2
      state: started
      when: ansible _distribution == "Ubuntu" or ansible _distribution == "Debian"

  - name: Enable Apache2
    service:
      name: apache2
      enabled: yes
      when: ansible _distribution == "Ubuntu" or ansible _distribution == "Debian"
...
